import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "~/components/navbar";
import { ApolloProvider } from "@apollo/client";
import apolloClient from "../lib/apollo";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloProvider client={apolloClient}>
        <UserProvider>
          <body className={`font-sans ${inter.variable} bg-[#034144]`}>
            <Navbar />
            {children}
          </body>
        </UserProvider>
      </ApolloProvider>
    </html>
  );
}
